// POST : CREAR
#POST http://localhost:8080/customers
#Content-Type: application/json
#
#{
"nameCustomer": "Edward",
 "dni": "12345678",
 "phone": "987654321",
"email": "edward@gmail.com",
"status": true
}

