
// POST : CREAR
#POST http://localhost:8080/customers
#Content-Type: application/json
#
#{
#  "nameCustomer": "Edward",
#  "dni": "12345678",
#  "phone": "987654321",
#  "email": "edwardgmail.com",
#  "status": true
#}

// GET : OBTENER TODO
#GET http://localhost:8080/employees

// GET : OBTENER POR ID
#GET http://localhost:8080/customers/1

// PUT : ACTUALIZAR CLIENTE
#PUT http://localhost:8080/customers/1
#Content-Type: application/json
#
#{
#  "nameCustomer": "Edward Actualizado",
#  "dni": "87654321",
#  "phone": "999999999",
#  "email": "edwardstevengmail.com",
#  "status": false
#}

// DELETE : ELIMINAR
#DELETE http://localhost:8080/customers/1


#POST http://localhost:8080/product-categories
#Content-Type: application/json
#
#{
#  "name": "Insumo",
#  "description": "Productos para hornear o preparar.",
#  "status": true
#}


#POST http://localhost:8080/products
#Content-Type: application/json
#
#{
#  "name": "Torta",
#  "description": "Torta simple",
#  "salePrice": 45.00,
#  "productionCost": 27.00,
#  "type": "Dulce",
#  "unitMeasure": "Kg",
#  "status": true,
#  "category": {
#    "idCategory": 1
#  }
#}


#POST http://localhost:8080/suppliers
#Content-Type: application/json
#
#{
#  "businessName": "Insumos San José SAC",
#  "ruc": "20123456789",
#  "phone": "987654321",
#  "email": "contacto@panificadora.com",
#  "address": "Av. Los Pinos 123 - Trujillo",
#  "status": true
#}


#POST http://localhost:8080/employees
#Content-Type: application/json
#
#{
#  "firstName": "Pachacutec",
#  "lastName": "Mendoza",
#  "dni": "12345678",
#  "phone": "987654321",
#  "position": "Administrador",
#  "status": true
#}

